# Google Cloud App Engine Configuration
runtime: nodejs20

# Instance configuration
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.65

# Environment variables
env_variables:
  EMAIL_USER: "safety@customworkforcesolutionsllc.com"
  EMAIL_PASS: "ylgy sxjp jswy knej"
  NODE_ENV: "production"
  ALLOWED_ORIGINS: "*"
  RATE_LIMIT_WINDOW_MS: "3600000"
  RATE_LIMIT_MAX_REQUESTS: "10"

# Handlers
handlers:
  - url: /.*
    script: auto
    secure: always
